
security_scrip_download_url = "https://images.dhan.co/api-data/api-scrip-master.csv"
client_id = "1100323569"
client_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJkaGFuIiwicGFydG5lcklkIjoiIiwiZXhwIjoxNzI0MjM4ODE4LCJ0b2tlbkNvbnN1bWVyVHlwZSI6IlNFTEYiLCJ3ZWJob29rVXJsIjoiIiwiZGhhbkNsaWVudElkIjoiMTEwMDMyMzU2OSJ9.wFZnRWontyfAlYEq_QewSU2mIUtL9DGuEIFbPyNvwBiXw5gIZbHfnAtnLTdzwOnJngsqH5Cp6yTYOxAXUeAleQ"
class DefaultExpiry:
    current = True


